# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
env:
  matrix:
    - TEST_DEVICE="iPhone 8,OS=11.0"
    - TEST_DEVICE="iPhone 8,OS=10.3"
    - TEST_DEVICE="iPhone 8,OS=9.3"
script:
- set -o pipefail && xcodebuild test -workspace Example/PluggableApplicationDelegate.xcworkspace -scheme PluggableApplicationDelegate-Example -sdk iphonesimulator11.0 -destination "platform=iOS Simulator,name=$TEST_DEVICE" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --swift-version=4.0
